#jwt.secret='[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

#spring.datasource.url=jdbc:mysql://localhost:3306/ecommercedbapp?serverTimezone=GMT-6
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

#Multipart file config
#spring.servlet.multipart.enabled=true
# Threshold after which files are written to disk.
#spring.servlet.multipart.file-size-threshold=2KB
# Max file size.
#spring.servlet.multipart.max-file-size=800MB
# Max Request Size
#spring.servlet.multipart.max-request-size=800MB

jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercedbapp?serverTimezone=GMT-6
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
        multipart:
          enabled: true
          file-size-threshold: 2KB
          max-file-size: 800MB
          max-request-size: 800MB
