package com.ecommerce.app.enumType;

public enum Mygeneration {
	
	FIRST_GENERATION , SECOND_GENERATION , THIRD_GENERATION , FOURTH_GENERATION , FIFTH_GENERATION , SIXTH_GENERATION , SEVENTH_GENERATION , EIGHTH_GENERATION , NINTH_GENERATION , TENTH_GENERATION

}
